// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: service.trade-account/proto/tradeaccount.proto

package tradeaccountproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradeaccountClient is the client API for Tradeaccount service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeaccountClient interface {
	/// --- Accounts --- ///
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	ReadAccount(ctx context.Context, in *ReadAccountRequest, opts ...grpc.CallOption) (*ReadAccountResponse, error)
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error)
	PageAccount(ctx context.Context, in *PageAccountRequest, opts ...grpc.CallOption) (*PageAccountResponse, error)
	/// --- Venue Account --- ///
	AddVenueAccount(ctx context.Context, in *AddVenueAccountRequest, opts ...grpc.CallOption) (*AddVenueAccountResponse, error)
	CreateOrUpdateInternalVenueAccount(ctx context.Context, in *CreateOrUpdateInternalVenueAccountRequest, opts ...grpc.CallOption) (*CreateOrUpdateInternalVenueAccountResponse, error)
	ListVenueAccounts(ctx context.Context, in *ListVenueAccountsRequest, opts ...grpc.CallOption) (*ListVenueAccountsResponse, error)
	ReadVenueAccountByVenueAccountID(ctx context.Context, in *ReadVenueAccountByVenueAccountIDRequest, opts ...grpc.CallOption) (*ReadVenueAccountByVenueAccountIDResponse, error)
	ReadVenueAccountByVenueAccountDetails(ctx context.Context, in *ReadVenueAccountByVenueAccountDetailsRequest, opts ...grpc.CallOption) (*ReadVenueAccountByVenueAccountDetailsResponse, error)
	ReadPrimaryVenueAccountByUserID(ctx context.Context, in *ReadPrimaryVenueAccountByUserIDRequest, opts ...grpc.CallOption) (*ReadPrimaryVenueAccountByUserIDResponse, error)
	ReadInternalVenueAccount(ctx context.Context, in *ReadInternalVenueAccountRequest, opts ...grpc.CallOption) (*ReadInternalVenueAccountResponse, error)
}

type tradeaccountClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeaccountClient(cc grpc.ClientConnInterface) TradeaccountClient {
	return &tradeaccountClient{cc}
}

func (c *tradeaccountClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) ReadAccount(ctx context.Context, in *ReadAccountRequest, opts ...grpc.CallOption) (*ReadAccountResponse, error) {
	out := new(ReadAccountResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/ReadAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) UpdateAccount(ctx context.Context, in *UpdateAccountRequest, opts ...grpc.CallOption) (*UpdateAccountResponse, error) {
	out := new(UpdateAccountResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/UpdateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) PageAccount(ctx context.Context, in *PageAccountRequest, opts ...grpc.CallOption) (*PageAccountResponse, error) {
	out := new(PageAccountResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/PageAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) AddVenueAccount(ctx context.Context, in *AddVenueAccountRequest, opts ...grpc.CallOption) (*AddVenueAccountResponse, error) {
	out := new(AddVenueAccountResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/AddVenueAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) CreateOrUpdateInternalVenueAccount(ctx context.Context, in *CreateOrUpdateInternalVenueAccountRequest, opts ...grpc.CallOption) (*CreateOrUpdateInternalVenueAccountResponse, error) {
	out := new(CreateOrUpdateInternalVenueAccountResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/CreateOrUpdateInternalVenueAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) ListVenueAccounts(ctx context.Context, in *ListVenueAccountsRequest, opts ...grpc.CallOption) (*ListVenueAccountsResponse, error) {
	out := new(ListVenueAccountsResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/ListVenueAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) ReadVenueAccountByVenueAccountID(ctx context.Context, in *ReadVenueAccountByVenueAccountIDRequest, opts ...grpc.CallOption) (*ReadVenueAccountByVenueAccountIDResponse, error) {
	out := new(ReadVenueAccountByVenueAccountIDResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/ReadVenueAccountByVenueAccountID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) ReadVenueAccountByVenueAccountDetails(ctx context.Context, in *ReadVenueAccountByVenueAccountDetailsRequest, opts ...grpc.CallOption) (*ReadVenueAccountByVenueAccountDetailsResponse, error) {
	out := new(ReadVenueAccountByVenueAccountDetailsResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/ReadVenueAccountByVenueAccountDetails", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) ReadPrimaryVenueAccountByUserID(ctx context.Context, in *ReadPrimaryVenueAccountByUserIDRequest, opts ...grpc.CallOption) (*ReadPrimaryVenueAccountByUserIDResponse, error) {
	out := new(ReadPrimaryVenueAccountByUserIDResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/ReadPrimaryVenueAccountByUserID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeaccountClient) ReadInternalVenueAccount(ctx context.Context, in *ReadInternalVenueAccountRequest, opts ...grpc.CallOption) (*ReadInternalVenueAccountResponse, error) {
	out := new(ReadInternalVenueAccountResponse)
	err := c.cc.Invoke(ctx, "/tradeaccount/ReadInternalVenueAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeaccountServer is the server API for Tradeaccount service.
// All implementations must embed UnimplementedTradeaccountServer
// for forward compatibility
type TradeaccountServer interface {
	/// --- Accounts --- ///
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	ReadAccount(context.Context, *ReadAccountRequest) (*ReadAccountResponse, error)
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountResponse, error)
	PageAccount(context.Context, *PageAccountRequest) (*PageAccountResponse, error)
	/// --- Venue Account --- ///
	AddVenueAccount(context.Context, *AddVenueAccountRequest) (*AddVenueAccountResponse, error)
	CreateOrUpdateInternalVenueAccount(context.Context, *CreateOrUpdateInternalVenueAccountRequest) (*CreateOrUpdateInternalVenueAccountResponse, error)
	ListVenueAccounts(context.Context, *ListVenueAccountsRequest) (*ListVenueAccountsResponse, error)
	ReadVenueAccountByVenueAccountID(context.Context, *ReadVenueAccountByVenueAccountIDRequest) (*ReadVenueAccountByVenueAccountIDResponse, error)
	ReadVenueAccountByVenueAccountDetails(context.Context, *ReadVenueAccountByVenueAccountDetailsRequest) (*ReadVenueAccountByVenueAccountDetailsResponse, error)
	ReadPrimaryVenueAccountByUserID(context.Context, *ReadPrimaryVenueAccountByUserIDRequest) (*ReadPrimaryVenueAccountByUserIDResponse, error)
	ReadInternalVenueAccount(context.Context, *ReadInternalVenueAccountRequest) (*ReadInternalVenueAccountResponse, error)
	mustEmbedUnimplementedTradeaccountServer()
}

// UnimplementedTradeaccountServer must be embedded to have forward compatible implementations.
type UnimplementedTradeaccountServer struct {
}

func (UnimplementedTradeaccountServer) ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (UnimplementedTradeaccountServer) ReadAccount(context.Context, *ReadAccountRequest) (*ReadAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadAccount not implemented")
}
func (UnimplementedTradeaccountServer) CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (UnimplementedTradeaccountServer) UpdateAccount(context.Context, *UpdateAccountRequest) (*UpdateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateAccount not implemented")
}
func (UnimplementedTradeaccountServer) PageAccount(context.Context, *PageAccountRequest) (*PageAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageAccount not implemented")
}
func (UnimplementedTradeaccountServer) AddVenueAccount(context.Context, *AddVenueAccountRequest) (*AddVenueAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddVenueAccount not implemented")
}
func (UnimplementedTradeaccountServer) CreateOrUpdateInternalVenueAccount(context.Context, *CreateOrUpdateInternalVenueAccountRequest) (*CreateOrUpdateInternalVenueAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateOrUpdateInternalVenueAccount not implemented")
}
func (UnimplementedTradeaccountServer) ListVenueAccounts(context.Context, *ListVenueAccountsRequest) (*ListVenueAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListVenueAccounts not implemented")
}
func (UnimplementedTradeaccountServer) ReadVenueAccountByVenueAccountID(context.Context, *ReadVenueAccountByVenueAccountIDRequest) (*ReadVenueAccountByVenueAccountIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadVenueAccountByVenueAccountID not implemented")
}
func (UnimplementedTradeaccountServer) ReadVenueAccountByVenueAccountDetails(context.Context, *ReadVenueAccountByVenueAccountDetailsRequest) (*ReadVenueAccountByVenueAccountDetailsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadVenueAccountByVenueAccountDetails not implemented")
}
func (UnimplementedTradeaccountServer) ReadPrimaryVenueAccountByUserID(context.Context, *ReadPrimaryVenueAccountByUserIDRequest) (*ReadPrimaryVenueAccountByUserIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPrimaryVenueAccountByUserID not implemented")
}
func (UnimplementedTradeaccountServer) ReadInternalVenueAccount(context.Context, *ReadInternalVenueAccountRequest) (*ReadInternalVenueAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadInternalVenueAccount not implemented")
}
func (UnimplementedTradeaccountServer) mustEmbedUnimplementedTradeaccountServer() {}

// UnsafeTradeaccountServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeaccountServer will
// result in compilation errors.
type UnsafeTradeaccountServer interface {
	mustEmbedUnimplementedTradeaccountServer()
}

func RegisterTradeaccountServer(s grpc.ServiceRegistrar, srv TradeaccountServer) {
	s.RegisterService(&Tradeaccount_ServiceDesc, srv)
}

func _Tradeaccount_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_ReadAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).ReadAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/ReadAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).ReadAccount(ctx, req.(*ReadAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_UpdateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).UpdateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/UpdateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).UpdateAccount(ctx, req.(*UpdateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_PageAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).PageAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/PageAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).PageAccount(ctx, req.(*PageAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_AddVenueAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddVenueAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).AddVenueAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/AddVenueAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).AddVenueAccount(ctx, req.(*AddVenueAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_CreateOrUpdateInternalVenueAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrUpdateInternalVenueAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).CreateOrUpdateInternalVenueAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/CreateOrUpdateInternalVenueAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).CreateOrUpdateInternalVenueAccount(ctx, req.(*CreateOrUpdateInternalVenueAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_ListVenueAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListVenueAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).ListVenueAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/ListVenueAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).ListVenueAccounts(ctx, req.(*ListVenueAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_ReadVenueAccountByVenueAccountID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadVenueAccountByVenueAccountIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).ReadVenueAccountByVenueAccountID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/ReadVenueAccountByVenueAccountID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).ReadVenueAccountByVenueAccountID(ctx, req.(*ReadVenueAccountByVenueAccountIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_ReadVenueAccountByVenueAccountDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadVenueAccountByVenueAccountDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).ReadVenueAccountByVenueAccountDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/ReadVenueAccountByVenueAccountDetails",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).ReadVenueAccountByVenueAccountDetails(ctx, req.(*ReadVenueAccountByVenueAccountDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_ReadPrimaryVenueAccountByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadPrimaryVenueAccountByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).ReadPrimaryVenueAccountByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/ReadPrimaryVenueAccountByUserID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).ReadPrimaryVenueAccountByUserID(ctx, req.(*ReadPrimaryVenueAccountByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeaccount_ReadInternalVenueAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadInternalVenueAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeaccountServer).ReadInternalVenueAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeaccount/ReadInternalVenueAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeaccountServer).ReadInternalVenueAccount(ctx, req.(*ReadInternalVenueAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tradeaccount_ServiceDesc is the grpc.ServiceDesc for Tradeaccount service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tradeaccount_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradeaccount",
	HandlerType: (*TradeaccountServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListAccounts",
			Handler:    _Tradeaccount_ListAccounts_Handler,
		},
		{
			MethodName: "ReadAccount",
			Handler:    _Tradeaccount_ReadAccount_Handler,
		},
		{
			MethodName: "CreateAccount",
			Handler:    _Tradeaccount_CreateAccount_Handler,
		},
		{
			MethodName: "UpdateAccount",
			Handler:    _Tradeaccount_UpdateAccount_Handler,
		},
		{
			MethodName: "PageAccount",
			Handler:    _Tradeaccount_PageAccount_Handler,
		},
		{
			MethodName: "AddVenueAccount",
			Handler:    _Tradeaccount_AddVenueAccount_Handler,
		},
		{
			MethodName: "CreateOrUpdateInternalVenueAccount",
			Handler:    _Tradeaccount_CreateOrUpdateInternalVenueAccount_Handler,
		},
		{
			MethodName: "ListVenueAccounts",
			Handler:    _Tradeaccount_ListVenueAccounts_Handler,
		},
		{
			MethodName: "ReadVenueAccountByVenueAccountID",
			Handler:    _Tradeaccount_ReadVenueAccountByVenueAccountID_Handler,
		},
		{
			MethodName: "ReadVenueAccountByVenueAccountDetails",
			Handler:    _Tradeaccount_ReadVenueAccountByVenueAccountDetails_Handler,
		},
		{
			MethodName: "ReadPrimaryVenueAccountByUserID",
			Handler:    _Tradeaccount_ReadPrimaryVenueAccountByUserID_Handler,
		},
		{
			MethodName: "ReadInternalVenueAccount",
			Handler:    _Tradeaccount_ReadInternalVenueAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.trade-account/proto/tradeaccount.proto",
}
