version: "3.9"

services:
  service.agentsmith:
    build:
      context: ./service.agentsmith/
      dockerfile: ./Dockerfile
    image: agentsmith.service.agentsmith
    environment:
      - AGENTSMITH_OPENAI_API_KEY=${AGENTSMITH_OPENAI_API_KEY}
