version: "3.9"

services:
  ### --- Services --- ###
  service.openai:
    hostname: sasha-service-openai
    image: sasha.service.openai
    profiles:
      - backend
  service.github:
    hostname: sasha-service-github
    image: sasha.service.github
    profiles:
      - backend
  service.agentsmith:
    build:
      context: ./service.agentsmith/
      dockerfile: ./Dockerfile
    image: agentsmith.service.agentsmith
    profiles:
      - backend
