// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: service.trade-engine/proto/tradeengine.proto

package tradeengineproto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TradeengineClient is the client API for Tradeengine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TradeengineClient interface {
	CreateTradeStrategy(ctx context.Context, in *CreateTradeStrategyRequest, opts ...grpc.CallOption) (*CreateTradeStrategyResponse, error)
	ExecuteTradeStrategyForParticipant(ctx context.Context, in *ExecuteTradeStrategyForParticipantRequest, opts ...grpc.CallOption) (*ExecuteTradeStrategyForParticipantResponse, error)
	ReadTradeStrategyByTradeStrategyID(ctx context.Context, in *ReadTradeStrategyByTradeStrategyIDRequest, opts ...grpc.CallOption) (*ReadTradeStrategyByTradeStrategyIDResponse, error)
	ListAvailableVenues(ctx context.Context, in *ListAvailableVenuesRequest, opts ...grpc.CallOption) (*ListAvailableVenuesResponse, error)
}

type tradeengineClient struct {
	cc grpc.ClientConnInterface
}

func NewTradeengineClient(cc grpc.ClientConnInterface) TradeengineClient {
	return &tradeengineClient{cc}
}

func (c *tradeengineClient) CreateTradeStrategy(ctx context.Context, in *CreateTradeStrategyRequest, opts ...grpc.CallOption) (*CreateTradeStrategyResponse, error) {
	out := new(CreateTradeStrategyResponse)
	err := c.cc.Invoke(ctx, "/tradeengine/CreateTradeStrategy", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeengineClient) ExecuteTradeStrategyForParticipant(ctx context.Context, in *ExecuteTradeStrategyForParticipantRequest, opts ...grpc.CallOption) (*ExecuteTradeStrategyForParticipantResponse, error) {
	out := new(ExecuteTradeStrategyForParticipantResponse)
	err := c.cc.Invoke(ctx, "/tradeengine/ExecuteTradeStrategyForParticipant", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeengineClient) ReadTradeStrategyByTradeStrategyID(ctx context.Context, in *ReadTradeStrategyByTradeStrategyIDRequest, opts ...grpc.CallOption) (*ReadTradeStrategyByTradeStrategyIDResponse, error) {
	out := new(ReadTradeStrategyByTradeStrategyIDResponse)
	err := c.cc.Invoke(ctx, "/tradeengine/ReadTradeStrategyByTradeStrategyID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tradeengineClient) ListAvailableVenues(ctx context.Context, in *ListAvailableVenuesRequest, opts ...grpc.CallOption) (*ListAvailableVenuesResponse, error) {
	out := new(ListAvailableVenuesResponse)
	err := c.cc.Invoke(ctx, "/tradeengine/ListAvailableVenues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TradeengineServer is the server API for Tradeengine service.
// All implementations must embed UnimplementedTradeengineServer
// for forward compatibility
type TradeengineServer interface {
	CreateTradeStrategy(context.Context, *CreateTradeStrategyRequest) (*CreateTradeStrategyResponse, error)
	ExecuteTradeStrategyForParticipant(context.Context, *ExecuteTradeStrategyForParticipantRequest) (*ExecuteTradeStrategyForParticipantResponse, error)
	ReadTradeStrategyByTradeStrategyID(context.Context, *ReadTradeStrategyByTradeStrategyIDRequest) (*ReadTradeStrategyByTradeStrategyIDResponse, error)
	ListAvailableVenues(context.Context, *ListAvailableVenuesRequest) (*ListAvailableVenuesResponse, error)
	mustEmbedUnimplementedTradeengineServer()
}

// UnimplementedTradeengineServer must be embedded to have forward compatible implementations.
type UnimplementedTradeengineServer struct {
}

func (UnimplementedTradeengineServer) CreateTradeStrategy(context.Context, *CreateTradeStrategyRequest) (*CreateTradeStrategyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTradeStrategy not implemented")
}
func (UnimplementedTradeengineServer) ExecuteTradeStrategyForParticipant(context.Context, *ExecuteTradeStrategyForParticipantRequest) (*ExecuteTradeStrategyForParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteTradeStrategyForParticipant not implemented")
}
func (UnimplementedTradeengineServer) ReadTradeStrategyByTradeStrategyID(context.Context, *ReadTradeStrategyByTradeStrategyIDRequest) (*ReadTradeStrategyByTradeStrategyIDResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadTradeStrategyByTradeStrategyID not implemented")
}
func (UnimplementedTradeengineServer) ListAvailableVenues(context.Context, *ListAvailableVenuesRequest) (*ListAvailableVenuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAvailableVenues not implemented")
}
func (UnimplementedTradeengineServer) mustEmbedUnimplementedTradeengineServer() {}

// UnsafeTradeengineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TradeengineServer will
// result in compilation errors.
type UnsafeTradeengineServer interface {
	mustEmbedUnimplementedTradeengineServer()
}

func RegisterTradeengineServer(s grpc.ServiceRegistrar, srv TradeengineServer) {
	s.RegisterService(&Tradeengine_ServiceDesc, srv)
}

func _Tradeengine_CreateTradeStrategy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTradeStrategyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeengineServer).CreateTradeStrategy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeengine/CreateTradeStrategy",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeengineServer).CreateTradeStrategy(ctx, req.(*CreateTradeStrategyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeengine_ExecuteTradeStrategyForParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteTradeStrategyForParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeengineServer).ExecuteTradeStrategyForParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeengine/ExecuteTradeStrategyForParticipant",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeengineServer).ExecuteTradeStrategyForParticipant(ctx, req.(*ExecuteTradeStrategyForParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeengine_ReadTradeStrategyByTradeStrategyID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadTradeStrategyByTradeStrategyIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeengineServer).ReadTradeStrategyByTradeStrategyID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeengine/ReadTradeStrategyByTradeStrategyID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeengineServer).ReadTradeStrategyByTradeStrategyID(ctx, req.(*ReadTradeStrategyByTradeStrategyIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Tradeengine_ListAvailableVenues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAvailableVenuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TradeengineServer).ListAvailableVenues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/tradeengine/ListAvailableVenues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TradeengineServer).ListAvailableVenues(ctx, req.(*ListAvailableVenuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Tradeengine_ServiceDesc is the grpc.ServiceDesc for Tradeengine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Tradeengine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "tradeengine",
	HandlerType: (*TradeengineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateTradeStrategy",
			Handler:    _Tradeengine_CreateTradeStrategy_Handler,
		},
		{
			MethodName: "ExecuteTradeStrategyForParticipant",
			Handler:    _Tradeengine_ExecuteTradeStrategyForParticipant_Handler,
		},
		{
			MethodName: "ReadTradeStrategyByTradeStrategyID",
			Handler:    _Tradeengine_ReadTradeStrategyByTradeStrategyID_Handler,
		},
		{
			MethodName: "ListAvailableVenues",
			Handler:    _Tradeengine_ListAvailableVenues_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.trade-engine/proto/tradeengine.proto",
}
