// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// DiscordClient is an autogenerated mock type for the DiscordClient type
type DiscordClient struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, message, channelID
func (_m *DiscordClient) Send(ctx context.Context, message string, channelID string) error {
	ret := _m.Called(ctx, message, channelID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, message, channelID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SendPrivateMessage provides a mock function with given fields: ctx, message, userID
func (_m *DiscordClient) SendPrivateMessage(ctx context.Context, message string, userID string) error {
	ret := _m.Called(ctx, message, userID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, message, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Subscribe provides a mock function with given fields: ctx, subscriberID
func (_m *DiscordClient) Subscribe(ctx context.Context, subscriberID string) error {
	ret := _m.Called(ctx, subscriberID)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = rf(ctx, subscriberID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
